version: '2'

networks:
  test:

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    networks:
      test:
    ports:
      - "4848:4848"

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    networks:
      test:
    command: server
