
package de.uniba.wiai.ktr.dynoff_wsdlstub;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "serverFault", targetNamespace = "http://webservice/")
public class ServerFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ServerFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ServerFault_Exception(String message, ServerFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ServerFault_Exception(String message, ServerFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: de.uniba.wiai.ktr.dynoff_wsdlstub.ServerFault
     */
    public ServerFault getFaultInfo() {
        return faultInfo;
    }

}
