
package de.uniba.wiai.ktr.dynoff_wsdlstub;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WebServiceAccessService", targetNamespace = "http://webservice/", wsdlLocation = "http://ktr-mg:8080/dynOff-GlassfishWeb/WebServiceAccessService?wsdl")
public class WebServiceAccessService
    extends Service
{

    private final static URL WEBSERVICEACCESSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(de.uniba.wiai.ktr.dynoff_wsdlstub.WebServiceAccessService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = de.uniba.wiai.ktr.dynoff_wsdlstub.WebServiceAccessService.class.getResource(".");
            url = new URL(baseUrl, "http://ktr-mg:8080/dynOff-GlassfishWeb/WebServiceAccessService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://ktr-mg:8080/dynOff-GlassfishWeb/WebServiceAccessService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WEBSERVICEACCESSSERVICE_WSDL_LOCATION = url;
    }

    public WebServiceAccessService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceAccessService() {
        super(WEBSERVICEACCESSSERVICE_WSDL_LOCATION, new QName("http://webservice/", "WebServiceAccessService"));
    }

    /**
     * 
     * @return
     *     returns WebServiceAccess
     */
    @WebEndpoint(name = "WebServiceAccessPort")
    public WebServiceAccess getWebServiceAccessPort() {
        return super.getPort(new QName("http://webservice/", "WebServiceAccessPort"), WebServiceAccess.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceAccess
     */
    @WebEndpoint(name = "WebServiceAccessPort")
    public WebServiceAccess getWebServiceAccessPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice/", "WebServiceAccessPort"), WebServiceAccess.class, features);
    }

}
